--- #YAML:1.0
name:         Pod-Perldocs
version:      0.16
version_from: lib/Pod/Perldocs.pm
installdirs:  site
license:      perl
abstract:     view remote pod via Pod::Perldoc
author:
    - 'Randy Kobes <r.kobes@uwinnipeg.ca>'
requires:
    Pod::Perldoc:                  0
    LWP:                           0
distribution_type: module
provides:
  Pod::Perldocs:
    file: lib/Pod/Perldocs.pm
    version: 0.16
urls:
   license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://cpan-search.svn.sourceforge.net/viewvc/cpan-search/Pod-Perldocs/
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pod-Perldocs
  AnnoCPAN: http://annocpan.org/dist/Pod-Perldocs
  CPANForum: http://www.cpanforum.com/dist/Pod-Perldocs
  CPANTS: http://cpants.perl.org/dist/Pod-Perldocs
  Rating: http://cpanratings.perl.org/d/Pod-Perldocs
  SearchCPAN: http://search.cpan.org/~RKOBES/Pod-Perldocs/
  Testers: http://cpantesters.perl.org/show/Pod-Perldocs.html
  UWinnipeg: http://cpan.uwinnipeg.ca/dist/Pod-Perldocs
generated_by: Randy Kobes
